- 
  version: '{build}'
  branches:
    except:
    - master
  skip_tags: true
  image: Visual Studio 2015
  before_build:
  - cmd: nuget restore
  build:
    verbosity: normal
  test_script:
  - cmd: vstest.console /logger:Appveyor "C:\projects\streak\Streaks.Test\bin\Debug\Streaks.Test.dll" "C:\projects\streak\Streaks.Spec\bin\Debug\Streaks.Spec.dll" /testadapterpath:"C:\projects\streak"
- 
  version: 0.3.1.{build}
  branches:
    only:
    - master
  skip_tags: true
  configuration: Release
  image: Visual Studio 2015
  assembly_info:
    patch: true
    file: '**\VersionInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  before_build:
  - cmd: nuget restore
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: minimal
  test_script:
  - cmd: vstest.console /logger:Appveyor "C:\projects\streak\Streaks.Test\bin\Release\Streaks.Test.dll" "C:\projects\streak\Streaks.Spec\bin\Release\Streaks.Spec.dll" /testadapterpath:"C:\projects\streak"
  artifacts:
  - path: '**\*.nupkg'
    name: Nuget packages